[parity]
chain = "genesis.json"
base_path = "data/validator1"
[network]
port = 30300
reserved_peers = "reservedPeers"
[rpc]
interface = "192.168.1.6"
port = 8545
apis = ["all"]
[websockets]
port = 8456
interface = "192.168.1.6"
apis = ["all"]
hosts = ["*"]
origins = ["*"]
[ipc]
path = "data/validator1/validator1.ipc"
apis = ["all"]
[ui]
port = 8180
[account]
password = ["v1.pwd"]
[mining]
engine_signer = "0x43a905c936c814faff3d379519fe846a93659577"
reseal_on_txs = "none"
